### ISSUE TITLE
Header and filenames doubling values

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#59]
Header name for error margin appears to be doubling:
"Per Capita Income in the Past 12 Months (In 2013 Inflation-adjusted Dollars), Per capita income in the past 12 months (in 2013 inflation-adjusted dollars) (error margin)"

Also, filenames appear to be doubling the file extension. (User reports seeing
filename in the format "xxxblahblah.xlsx.xls"

Here is the resulting file (with the redundant extension removed): https://www.dropbox.com/s/7sbnkd04eu293fm/minimum_wage2013_01_2014-12-02T19_56_27.846616.xlsx?dl=0

**Comment by evz** [comment]
@tthibo The main reason why the header repeats that value is because the error margin is for a particular column and if a user decides to mance against something that has a ton of columns, one needs to know which error margin goes with which column. I realize it's verbose. I'm open to suggestions as to how to make sure the resulting spreadsheet is clear and doesn't have ridiculously long headers.

**Comment by tthibo** [comment]
This is my bad. I was submitting the bug report for someone else without looking at the headers closely enough. The headers aren't doubled; there's one for the value and one for MoE. That makes sense.
Sorry for the distraction.
