### ISSUE TITLE
Column header text doubled

### ISSUE THREAD

**Issue by tthibo** [associatedpress/geomancer#82]
There was a similar issue before that turned out to be just inclusion of MoE columns, but this
appears different -- the text of the column header appears to be duplicated:
Per Capita Income in the Past 12 Months (In 2013 Inflation-adjusted Dollars), Per capita income in the past 12 months (in 2013 inflation-adjusted dollars)

To replicate:
Upload act.xlsx from Examples and choose State geography
Select: Median Household Income in the Past 12 Months (In 2013 Inflation-adjusted Dollars)
The result:
Median Household Income in the Past 12 Months (In 2013 Inflation-adjusted Dollars), Median household income in the past 12 months (in 2013 inflation-adjusted dollars)

Also oddly, the margin of error header only includes the phrase "error margin" once, although the
rest of the header is repeated:
Median Household Income in the Past 12 Months (In 2013 Inflation-adjusted Dollars), Median household income in the past 12 months (in 2013 inflation-adjusted dollars) (error margin)

**Comment by cathydeng** [comment]
Hey Troy - looks like this is happening b/c of how censusreporter data is structured.

The census reporter mancer creates a cell name for the header by concatenating table name (aka stuff under 'Data from Census Reporter') & a detail name (aka what shows up under Columns that will be added) https://github.com/datamade/geomancer/blob/master/geomancer/mancers/census_reporter.py#L224
![screen shot 2015-03-04 at 11 12 58 am](https://cloud.githubusercontent.com/assets/1406537/6488960/82b7f0ee-c260-11e4-987a-b502e7038920.png)

For most tables (for example group quarters population), this is ok, b/c there isn't redundant content, & we need both pieces of info
![screen shot 2015-03-04 at 11 17 07 am](https://cloud.githubusercontent.com/assets/1406537/6488978/9d9a1612-c260-11e4-9e1d-cd1c75ac4b02.png)

But for per capita income, the table & detail names are redundant
![screen shot 2015-03-04 at 11 17 15 am](https://cloud.githubusercontent.com/assets/1406537/6488991/b4338624-c260-11e4-96f1-3a085dd271ec.png)

This same thing is also happening for median value
![screen shot 2015-03-04 at 11 17 29 am](https://cloud.githubusercontent.com/assets/1406537/6489007/cb003b4a-c260-11e4-9664-1087b9d138d9.png)

Because this is a census reporter thing, we'll have to make a manual fix. I'll adjust how header names are created for these specific tables.
