### ISSUE TITLE
Get AP registered BLS API key

### ISSUE THREAD

**Issue by evz** [associatedpress/geomancer#91]
The new BLS mancer will require an API key. It seems sensible to have this registered to an AP email address.

**Comment by tthibo** [comment]
Requested.

**Comment by tthibo** [comment]
Forwarded.

**Comment by hiles8500** [comment]
BLS QCEW open data does not require an API key.

**Comment by hiles8500** [comment]
Rephrased: Users of the BLS QCEW open data resource do not have to use API keys to get data from that BLS source.  Cathy Deng did some work recently using QCEW.

The BLS API delivers data from an Oracle database.  It does require an API key.  It holds only 5% of QCEW data due to volume issues. It serves out 100% of data for many other BLS streams that may be of interest to Geomancer.

**Comment by cathydeng** [comment]
hey David! in addition to the QCEW data, we're also using OES data from the BLS API

**Comment by hiles8500** [comment]
LAUS might be a good feed for you from that API.
